// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type PaymentsCouponRedemption struct {
	ID        string    `json:"id"`
	CouponID  string    `json:"coupon_id"`
	UserID    string    `json:"user_id"`
	OrderID   string    `json:"order_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PaymentsIdempotencyKey struct {
	Key       string    `json:"key"`
	BodyHash  string    `json:"body_hash"`
	OrderID   string    `json:"order_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PaymentsOrder struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	PassID          string    `json:"pass_id"`
	CouponID        *string   `json:"coupon_id"`
	AmountPaise     int64     `json:"amount_paise"`
	Currency        string    `json:"currency"`
	Status          string    `json:"status"`
	Provider        string    `json:"provider"`
	ProviderOrderID *string   `json:"provider_order_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ExpiresAt       time.Time `json:"expires_at"`
}

type PaymentsPaymentLock struct {
	UserID    string    `json:"user_id"`
	OrderID   string    `json:"order_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}
