// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type PaymentsIdempotencyKey struct {
	Key       string    `json:"key"`
	BodyHash  string    `json:"body_hash"`
	OrderID   string    `json:"order_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PaymentsOrder struct {
	ID              string    `json:"id"`
	BuyerID         string    `json:"buyer_id"`
	TotalPaise      int64     `json:"total_paise"`
	Currency        string    `json:"currency"`
	Status          string    `json:"status"`
	Provider        string    `json:"provider"`
	ProviderOrderID *string   `json:"provider_order_id"`
	BuyerPhone      string    `json:"buyer_phone"`
	BuyerEmail      string    `json:"buyer_email"`
	BuyerName       string    `json:"buyer_name"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ExpiresAt       time.Time `json:"expires_at"`
}
