// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payments.sql

package db

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO payments.orders (
    id, user_id, pass_id, coupon_id, amount_paise, currency,
    status, provider, provider_order_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, pass_id, coupon_id, amount_paise, currency, status, provider, provider_order_id, created_at, updated_at, expires_at
`

type CreateOrderParams struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	PassID          string    `json:"pass_id"`
	CouponID        *string   `json:"coupon_id"`
	AmountPaise     int64     `json:"amount_paise"`
	Currency        string    `json:"currency"`
	Status          string    `json:"status"`
	Provider        string    `json:"provider"`
	ProviderOrderID *string   `json:"provider_order_id"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.PassID,
		arg.CouponID,
		arg.AmountPaise,
		arg.Currency,
		arg.Status,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ExpiresAt,
	)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PassID,
		&i.CouponID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deletePaymentLock = `-- name: DeletePaymentLock :exec
DELETE FROM payments.payment_locks WHERE user_id = $1
`

func (q *Queries) DeletePaymentLock(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePaymentLock, userID)
	return err
}

const findIdempotencyKey = `-- name: FindIdempotencyKey :one
SELECT key, body_hash, order_id, created_at FROM payments.idempotency_keys WHERE key = $1
`

func (q *Queries) FindIdempotencyKey(ctx context.Context, key string) (PaymentsIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, findIdempotencyKey, key)
	var i PaymentsIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.BodyHash,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, pass_id, coupon_id, amount_paise, currency, status, provider, provider_order_id, created_at, updated_at, expires_at FROM payments.orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PassID,
		&i.CouponID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertCouponRedemption = `-- name: InsertCouponRedemption :one
INSERT INTO payments.coupon_redemptions (id, coupon_id, user_id, order_id)
VALUES ($1, $2, $3, $4)
RETURNING id, coupon_id, user_id, order_id, created_at
`

type InsertCouponRedemptionParams struct {
	ID       string `json:"id"`
	CouponID string `json:"coupon_id"`
	UserID   string `json:"user_id"`
	OrderID  string `json:"order_id"`
}

func (q *Queries) InsertCouponRedemption(ctx context.Context, arg InsertCouponRedemptionParams) (PaymentsCouponRedemption, error) {
	row := q.db.QueryRow(ctx, insertCouponRedemption,
		arg.ID,
		arg.CouponID,
		arg.UserID,
		arg.OrderID,
	)
	var i PaymentsCouponRedemption
	err := row.Scan(
		&i.ID,
		&i.CouponID,
		&i.UserID,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO payments.idempotency_keys (key, body_hash, order_id)
VALUES ($1, $2, $3)
RETURNING key, body_hash, order_id, created_at
`

type InsertIdempotencyKeyParams struct {
	Key      string `json:"key"`
	BodyHash string `json:"body_hash"`
	OrderID  string `json:"order_id"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (PaymentsIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey, arg.Key, arg.BodyHash, arg.OrderID)
	var i PaymentsIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.BodyHash,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE payments.orders
SET status = 'PAID', provider_order_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, pass_id, coupon_id, amount_paise, currency, status, provider, provider_order_id, created_at, updated_at, expires_at
`

type MarkOrderPaidParams struct {
	ID              string  `json:"id"`
	ProviderOrderID *string `json:"provider_order_id"`
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, arg.ID, arg.ProviderOrderID)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PassID,
		&i.CouponID,
		&i.AmountPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertPaymentLock = `-- name: UpsertPaymentLock :one
INSERT INTO payments.payment_locks (user_id, order_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET order_id = EXCLUDED.order_id, expires_at = EXCLUDED.expires_at
    WHERE payments.payment_locks.expires_at < now()   -- only steal an expired lock
RETURNING user_id, order_id, expires_at, created_at
`

type UpsertPaymentLockParams struct {
	UserID    string    `json:"user_id"`
	OrderID   string    `json:"order_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpsertPaymentLock(ctx context.Context, arg UpsertPaymentLockParams) (PaymentsPaymentLock, error) {
	row := q.db.QueryRow(ctx, upsertPaymentLock, arg.UserID, arg.OrderID, arg.ExpiresAt)
	var i PaymentsPaymentLock
	err := row.Scan(
		&i.UserID,
		&i.OrderID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const userHasPaidPass = `-- name: UserHasPaidPass :one
SELECT EXISTS (
    SELECT 1 FROM payments.orders
    WHERE user_id = $1 AND status = 'PAID'
) AS has_pass
`

func (q *Queries) UserHasPaidPass(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPaidPass, userID)
	var has_pass bool
	err := row.Scan(&has_pass)
	return has_pass, err
}
