// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO payments.orders (
    id, buyer_id, total_paise, currency, status, provider,
    provider_order_id, expires_at, buyer_phone, buyer_email, buyer_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, buyer_id, total_paise, currency, status, provider, provider_order_id, buyer_phone, buyer_email, buyer_name, created_at, updated_at, expires_at, paid_at
`

type CreateOrderParams struct {
	ID              string    `json:"id"`
	BuyerID         string    `json:"buyer_id"`
	TotalPaise      int64     `json:"total_paise"`
	Currency        string    `json:"currency"`
	Status          string    `json:"status"`
	Provider        string    `json:"provider"`
	ProviderOrderID *string   `json:"provider_order_id"`
	ExpiresAt       time.Time `json:"expires_at"`
	BuyerPhone      string    `json:"buyer_phone"`
	BuyerEmail      string    `json:"buyer_email"`
	BuyerName       string    `json:"buyer_name"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.BuyerID,
		arg.TotalPaise,
		arg.Currency,
		arg.Status,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ExpiresAt,
		arg.BuyerPhone,
		arg.BuyerEmail,
		arg.BuyerName,
	)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.TotalPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.BuyerPhone,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
	)
	return i, err
}

const findIdempotencyKey = `-- name: FindIdempotencyKey :one
SELECT key, body_hash, order_id, created_at FROM payments.idempotency_keys WHERE key = $1
`

func (q *Queries) FindIdempotencyKey(ctx context.Context, key string) (PaymentsIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, findIdempotencyKey, key)
	var i PaymentsIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.BodyHash,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, buyer_id, total_paise, currency, status, provider, provider_order_id, buyer_phone, buyer_email, buyer_name, created_at, updated_at, expires_at, paid_at FROM payments.orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.TotalPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.BuyerPhone,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByProviderOrderID = `-- name: GetOrderByProviderOrderID :one
SELECT id, buyer_id, total_paise, currency, status, provider, provider_order_id, buyer_phone, buyer_email, buyer_name, created_at, updated_at, expires_at, paid_at FROM payments.orders WHERE provider_order_id = $1
`

func (q *Queries) GetOrderByProviderOrderID(ctx context.Context, providerOrderID *string) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByProviderOrderID, providerOrderID)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.TotalPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.BuyerPhone,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
	)
	return i, err
}

const getOrderStatus = `-- name: GetOrderStatus :one
SELECT id, status, total_paise FROM payments.orders WHERE id = $1
`

type GetOrderStatusRow struct {
	ID         string `json:"id"`
	Status     string `json:"status"`
	TotalPaise int64  `json:"total_paise"`
}

func (q *Queries) GetOrderStatus(ctx context.Context, id string) (GetOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, getOrderStatus, id)
	var i GetOrderStatusRow
	err := row.Scan(&i.ID, &i.Status, &i.TotalPaise)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO payments.idempotency_keys (key, body_hash, order_id)
VALUES ($1, $2, $3)
RETURNING key, body_hash, order_id, created_at
`

type InsertIdempotencyKeyParams struct {
	Key      string `json:"key"`
	BodyHash string `json:"body_hash"`
	OrderID  string `json:"order_id"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (PaymentsIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey, arg.Key, arg.BodyHash, arg.OrderID)
	var i PaymentsIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.BodyHash,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const markOrderPaidIfActive = `-- name: MarkOrderPaidIfActive :one
UPDATE payments.orders
SET status = 'PAID', 
    paid_at = $2,
    updated_at = now()
WHERE id = $1 
  AND status = 'ACTIVE' 
  AND total_paise = $3
RETURNING id
`

type MarkOrderPaidIfActiveParams struct {
	ID         string             `json:"id"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	TotalPaise int64              `json:"total_paise"`
}

// Idempotent: only transitions ACTIVE → PAID when amount matches.
// Returns the row if transition happened, no rows otherwise.
func (q *Queries) MarkOrderPaidIfActive(ctx context.Context, arg MarkOrderPaidIfActiveParams) (string, error) {
	row := q.db.QueryRow(ctx, markOrderPaidIfActive, arg.ID, arg.PaidAt, arg.TotalPaise)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE payments.orders
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, buyer_id, total_paise, currency, status, provider, provider_order_id, buyer_phone, buyer_email, buyer_name, created_at, updated_at, expires_at, paid_at
`

type UpdateOrderStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (PaymentsOrder, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i PaymentsOrder
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.TotalPaise,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderOrderID,
		&i.BuyerPhone,
		&i.BuyerEmail,
		&i.BuyerName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
	)
	return i, err
}
