// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (PaymentsOrder, error)
	FindIdempotencyKey(ctx context.Context, key string) (PaymentsIdempotencyKey, error)
	GetOrder(ctx context.Context, id string) (PaymentsOrder, error)
	GetOrderByProviderOrderID(ctx context.Context, providerOrderID *string) (PaymentsOrder, error)
	GetOrderStatus(ctx context.Context, id string) (GetOrderStatusRow, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (PaymentsIdempotencyKey, error)
	// Idempotent: only transitions ACTIVE → PAID when amount matches.
	// Returns the row if transition happened, no rows otherwise.
	MarkOrderPaidIfActive(ctx context.Context, arg MarkOrderPaidIfActiveParams) (string, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (PaymentsOrder, error)
}

var _ Querier = (*Queries)(nil)
